// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe-FcK40F5sENF0_CeUqBTjUClOONebtQ',
    appId: '1:1068771102491:web:0af35921e2f161a36fcdbe',
    messagingSenderId: '1068771102491',
    projectId: 'cmananagerapp',
    authDomain: 'cmananagerapp.firebaseapp.com',
    storageBucket: 'cmananagerapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXnEbc0fLBvhL8xo93wKrM5Owt5nJmMk',
    appId: '1:1068771102491:android:0ac15508f58457786fcdbe',
    messagingSenderId: '1068771102491',
    projectId: 'cmananagerapp',
    storageBucket: 'cmananagerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2d9x_VTcVds29LXw8pQQz07noaFA0F0',
    appId: '1:1068771102491:ios:462502b55deb5c8f6fcdbe',
    messagingSenderId: '1068771102491',
    projectId: 'cmananagerapp',
    storageBucket: 'cmananagerapp.appspot.com',
    iosClientId: '1068771102491-1lj8gbce2haiot1uhvtolj6s7r6s41bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmanagerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz2d9x_VTcVds29LXw8pQQz07noaFA0F0',
    appId: '1:1068771102491:ios:462502b55deb5c8f6fcdbe',
    messagingSenderId: '1068771102491',
    projectId: 'cmananagerapp',
    storageBucket: 'cmananagerapp.appspot.com',
    iosClientId: '1068771102491-1lj8gbce2haiot1uhvtolj6s7r6s41bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmanagerapp',
  );
}
